# Generated by Django 3.1.5 on 2021-01-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='activeOrders',
            field=models.IntegerField(default=0),
        ),
    ]
