# Generated by Django 3.1.5 on 2021-01-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='maxActiveOrders',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(max_length=255, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('cuisine', models.CharField(choices=[('Chinese', 'Chinese'), ('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Italian', 'Italian')], max_length=50)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
