# Generated by Django 3.1.5 on 2021-01-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cusID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='dishID',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='resID',
            new_name='restaurant',
        ),
    ]
