# Generated by Django 3.1.5 on 2021-01-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_auto_20210114_1522'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=60)),
                ('order_activity', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=60)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('dish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.menu')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
            ],
        ),
    ]
