# Generated by Django 3.1.5 on 2021-01-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210118_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_activity',
            field=models.BooleanField(default=True),
        ),
    ]
