# Generated by Django 3.1.5 on 2021-01-18 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210118_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='dish_quantity',
            new_name='quantity',
        ),
    ]
