# Generated by Django 3.1.5 on 2021-01-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210118_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
